server:
  port: 8081
spring:
  datasource:
    url: jdbc:mariadb://144.24.67.233:3306/pinner_dev
    username: ${DB_ID}
    password: ${DB_PW}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop # TODO update 변경

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: "https://dev.pinner.dev"
            clientId: ${NAVER_CLIENT_ID}
            clientSecret: ${NAVER_CLIENT_SECRET}
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

path:
  image: images
  url: https://dev.pinner.dev
  