spring:
  profiles:
    active: local
  servlet:
    multipart: # 이미지 업로드 파일 제한 설정(기본 1MB)
      max-file-size: 10MB
      max-request-size: 10MB
token:
  app:
    jwtSecret: travelSecretKey
    jwtExpirationMs: 3600000  # Access Token (3600000ms = 1s)
    jwtRefreshExpirationMs: 1209600000 # Refresh Token (14일)
google-api-key: ${GOOGLE_API_KEY}
photo-service:
  provider: "memory"
