spring:
  profiles:
    active: local

token:
  app:
    jwtSecret: travelSecretKey
    jwtExpirationMs: 120000  # Access Token (60000 = 1m)
    jwtRefreshExpirationMs: 600000 # Refresh Token
google-api-key: ${GOOGLE_API_KEY}
