spring:
  profiles:
    active: local
  servlet:
    multipart: # 이미지 업로드 파일 제한 설정(기본 1MB)
      max-file-size: 10MB
      max-request-size: 10MB
token:
  app:
    jwtSecret: travelSecretKey
    jwtExpirationMs: 3600000
    jwtRefreshExpirationMs: 86400000