spring:
  datasource:
    url: jdbc:h2:~/pinner_local
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
      # 개발(validate , none) 운영 : none
  #    properties:
  #      hibernate.format_sql: true
  #    show-sql: true

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            clientId: ${NAVER_CLIENT_ID}
            clientSecret: ${NAVER_CLIENT_SECRET}
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

logging:
  level:
    #    org.hibernate.SQL: debug
    #    org.hibernate.type: trace
    org.springframework.web: TRACE
    org.springframework.security: TRACE

path:
  image: images
  url: http://localhost:8080