version: '3.9'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /home/ubuntu/app/pinner_dev/config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    user: "$UID:$GID"
    ports:
      - "3000:3000"
    volumes:
      - /home/ubuntu/app/pinner_dev/data/grafana:/var/lib/grafana
    restart: always
    depends_on:
      - prometheus