version: '3.9'

services:
  backend-dev:
    image: adg0609/pinner-be-dev:latest
    container_name: backend-dev
    expose:
      - 8081
    volumes:
      - /home/ubuntu/app/pinner_dev/images:/images
    environment:
      - DB_ID=
      - DB_PW=
      - GOOGLE_API_KEY=
      - NAVER_CLIENT_ID=
      - NAVER_CLIENT_SECRET=
      - GOOGLE_CLIENT_ID=
      - GOOGLE_CLIENT_SECRET=
      - GMAIL_ID=
      - GMAIL_PW=
      - SPRING_PROFILES_ACTIVE=dev
      - TZ=Asia/Seoul

  frontend-dev:
    image: adg0609/pinner-fe-dev:latest
    container_name: frontend-dev
    ports:
      - "80:80"
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - backend-dev
