name: deploy

on:
  push:
    paths:
     - 'tree/develop/travelmaprecode-fe/**'
     - 'tree/develop/travelmaprecode-be/**'
    branches: [ "develop" ]
  pull_request:
    paths:
     - 'travelmaprecode-fe/**'
     - 'travelmaprecode-be/**'
    branches: [ "develop" ]

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
    - name : Checkout Repository
      uses: actions/checkout@v2
    
    - name : Run Paths Filter
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          backend:
            - 'tree/develop/travelmaprecode-be/**'
          frontend:
            - 'tree/develop/travelmaprecode-fe/**'

  backend:
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest
    env:
      working-directory: /home/ubuntu/app/pinner_dev/pinner_be
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
    
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      
      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_DEV_HOST }}
          port: 22
          username: ${{ secrets.SSH_DEV_USERNAME }}
          key: ${{ secrets.SSH_DEV_RSA_KEY }}
          script: |
            echo "Backend 테스트 출력"
  
  frontend:
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    env:
      working-directory: /home/ubuntu/app/pinner_dev/pinner_fe
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_DEV_HOST }}
          port: 22
          username: ${{ secrets.SSH_DEV_USERNAME }}
          key: ${{ secrets.SSH_DEV_RSA_KEY }}
          script: |
            echo "Frontend 테스트 출력"
