name: deploy

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    paths:
     - 'travelmaprecode-fe/**'
     - 'travelmaprecode-be/**'
    branches: [ "develop" ]
  pull_request:
    paths:
     - 'travelmaprecode-fe/**'
     - 'travelmaprecode-be/**'
    branches: [ "develop" ]

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
      with:
        ref: develop
        repository: PARKJINHOH/TravelMapRecord
        token: ${{ secrets.TOKEN_GITHUB }}
    - name : Run Paths Filter
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          backend:
            - 'travelmaprecode-be/**'
          frontend:
            - 'travelmaprecode-fe/**'

  backend:
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest
    env:
      working-directory: /home/ubuntu/app/pinner_dev/pinner_be
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          ref: develop
          repository: PARKJINHOH/TravelMapRecord
          token: ${{ secrets.TOKEN_GITHUB }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew bootJar
